---
- name: SSH Commander
  hosts: mt-smb
  gather_facts: no
  strategy: free

  vars:
    mt_port:      22
    mt_username:  admin
    mt_password:  password
    mt_pkey_file: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Fotos
      mt_commands:
        host:      "{{ inventory_hostname }}"
        port:      "{{ mt_port }}"
        username:  "{{ mt_username }}"
        pkey_file: "{{ mt_pkey_file }}"
        commands:
          - /user group add name=ftp-read policy=ftp,read
          - /user add name=user password=pass group=ftp-read
        output:   /data/output/{{ inventory_hostname }}.csv
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
