---
- name: SSH Commander
  hosts: mt-smb
  gather_facts: no
  strategy: free

  vars:
    mt_port:     56022
    mt_username: itmanager
    mt_pkeyfile: /home/itmanager/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Add USER GROUP
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /user group
        action:   add
        propvals: name=ftp-read policy=ftp,read
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add USER
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /user
        action:   add
        propvals: name=anel password=anel group=ftp-read
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add USER GROUP
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /user group
        action:   add
        propvals: name=ftp policy=ftp,read,write
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add USER
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /user
        action:   add
        propvals: name=fotos password=a1999 group=ftp
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add IP ADDRESS
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /ip address
        action:   add
        propvals: address="192.168.111.11/32" interface=br-local network=192.168.111.11
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Set IP SERVICE FTP
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /ip service
        action:   set
        find:     ftp
        propvals: address=192.168.0.0/16 port=56021 disabled=no
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Set IP SMB
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /ip smb
        action:   set
        propvals: domain=ANEL enabled=yes interfaces=br-local
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add IP SMB SHARE
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /ip smb shares
        action:   add
        propvals: directory=/disk1/fotografies name=fotografies
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Add IP SMB USER
      mt_set:
        host:     "{{ inventory_hostname }}"
        port:     "{{ mt_port }}"
        username: "{{ mt_username }}"
        pkeyfile: "{{ mt_pkeyfile }}"
        branch:   /ip smb users
        action:   add
        propvals: name=anel password=anel read-only=yes
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
