---
- name: Mikrotik Setup
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     56022
    mt_username: itmanager
    mt_pkeyfile: /home/itmanager/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Setup
      mt_setup:
        host: "{{ inventory_hostname }}"
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Gather Facts - /system identity
      mt_facts:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /system identity
        properties: name
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result

    - name: Mikrotik - Gather Facts - /system resources
      mt_facts:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /system resource
        properties: version cpu cpu-count cpu-frequency write-sect-total bad-blocks architecture-name board-name
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
