---
- name: SSH Commander
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     22
    mt_username: admin
    mt_pkeyfile: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Command
      mt_commands:
        hostname:  "{{ inventory_hostname }}"
        port:      "{{ mt_port }}"
        username:  "{{ mt_username }}"
        pkeyfile:  "{{ mt_pkeyfile }}"
        command:   /export
        output:    /data/export/{{ inventory_hostname }}.rsc
        raw:       True
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
