---
- name: SSH Commander
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     22
    mt_username: admin
    mt_pkeyfile: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Add USER GROUP
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /user group
        action:     add
        propvals:   name=ftp policy=ftp,read,write
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Add USER
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /user
        action:     add
        propvals:   name=ftpuser password=ftpuser group=ftp
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Add IP ADDRESS
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip address
        action:     add
        propvals:   address="192.168.1.11/24" interface=ether1 network=192.168.1.0
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Set IP SERVICE FTP
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip service
        action:     set
        find:       ftp
        propvals:   address=192.168.1.0/24 port=21 disabled=no
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Set IP SMB
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip smb
        action:     set
        propvals:   domain=EXAMPLECOM enabled=yes interfaces=ether1
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Add IP SMB SHARE
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip smb shares
        action:     add
        propvals:   directory=/disk1/shares name=shares
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Add IP SMB USER
      mt_set:
        host:       "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip smb users
        action:     add
        propvals:   name=ftp password=ftp read-only=yes
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
