---
- name: SSH Commander
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     22
    mt_username: admin
    mt_pkeyfile: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Upload
      mt_upload:
        hostname:   "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        local:      "/data"
        remote:     "/dir1/dir2/dir3/"
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
