---
- name: SSH Commander
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     22
    mt_username: admin
    mt_pkeyfile: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Set Value
      mt_set:
        hostname:   "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /ip firewall address-list
        action:     set
        propvals:   disabled=no
        find:       list=ntp-servers address=192.168.1.11
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
