---
- name: Mikrotik Setup
  hosts: mt-test
  gather_facts: no
  strategy: free

  vars:
    mt_port:     22
    mt_username: admin
    mt_pkeyfile: /home/admin/.ssh/id_rsa

  tasks:
    - name: Mikrotik - Setup
      mikrotik_setup:
        hostname:   "{{ inventory_hostname }}"
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Collect Facts - /system identity
      mikrotik_ssh_facts:
        hostname:   "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /system identity
        properties: name
      delegate_to: 127.0.0.1
      register: result

    - name: Mikrotik - Collect Facts - /system resources
      mikrotik_ssh_facts:
        hostname:   "{{ inventory_hostname }}"
        port:       "{{ mt_port }}"
        username:   "{{ mt_username }}"
        pkeyfile:   "{{ mt_pkeyfile }}"
        branch:     /system resource
        properties: version cpu cpu-count cpu-frequency write-sect-total bad-blocks architecture-name board-name
      delegate_to: 127.0.0.1
      register: result

    - debug: var=result
